
baseURL = "https://unicornumr1314.github.io/"
title = "Uni星人"
languageCode = "zh-CN"

theme = "DoIt"

[params]
enablePWA = true
fingerprint = "sha512"

[params.author]
name = "Uni星人"
email = ""
link = "https://github.com/UnicornUMR1314"
avatar = ""

[params.header]
themeChangeMode = "select"
  [params.header.title]
  logo = ""
  name = "Uni星人"
  pre = ""
  post = ""
  typeit = false

[params.footer]
enable = true
custom = ''
hugo = true
hostedOn = ''
copyright = true
author = true
since = 2025
icp = ""
license = ''

[params.search]
enable = true
type = "fuse"
maxResultLength = 10
highlightTag = "mark"
absoluteURL = false
contentLength = 400

[params.search.fuse]
isCaseSensitive = false
minMatchCharLength = 2
findAllMatches = false
location = 0
threshold = 0.3
distance = 100
ignoreLocation = true
useExtendedSearch = false
ignoreFieldNorm = false

[params.page.comment]
enable = true

[params.page.comment.giscus]
enable = true
dataRepo = "UnicornUMR1314/unicornumr1314.github.io"
dataRepoId = "R_kgDOOTJ8uw"
dataCategory = "General"
dataCategoryId = "DIC_kwDOOTJ8u84CoxOQ"
dataMapping = "pathname"
dataStrict = "0"
dataReactionsEnabled = "1"
dataEmitMetadata = "0"
dataInputPosition = "bottom"
lightTheme = "light"
darkTheme = "dark"
dataLang = "zh-CN"
dataLoading = "lazy"

[params.page]
seriesNavigation = true
  [params.page.header]
    [params.page.header.number]
      enable = true
        [params.page.header.number.format]
        h2 = "{h2} {title}"
        h3 = "{h2}.{h3} {title}"
        h4 = "{h2}.{h3}.{h4} {title}"
        h5 = "{h2}.{h3}.{h4}.{h5} {title}"
        h6 = "{h2}.{h3}.{h4}.{h5}.{h6} {title}"
  [params.page.toc]
    enable = true
    keepStatic = false
    auto = true
  [params.page.table]
    sort = true
  [params.page.instantpage]
    enable = true
  [params.page.math]
    enable = true
    blockLeftDelimiter = "\\["
    blockRightDelimiter = "\\]"
    inlineLeftDelimiter = "\\("
    inlineRightDelimiter = "\\)"
    copyTex = true
    mhchem = true
  [params.page.plantuml]
    server = "https://www.plantuml.com/plantuml"
  [params.page.share]
    enable = true
    Weibo = true
    Twitter = true
    Telegram = true
    Line = true
    HackerNews = true
    Mastodon = true

[params.home]
rss = 10
  [params.home.profile]
  enable = true
  gravatarEmail = ""
  avatarURL = ""
  avatarLinkURL = ""
  title = ""
  subtitle = "一个简洁、优雅且高效的 Hugo 主题"
  typeit = false
  social = true

[params.social]
GitHub = "UnicornUMR1314"
RSS = true
Zhihu = ""
Bilibili = ""
Twitter = ""
 Weibo = ""
 Telegram = ""
 Email = ""
 Linkedin = ""
 Mastodon = ""
 QQ = ""
 WeChat = ""
 Steam = ""
 Reddit = ""
 Instagram = ""

defaultContentLanguage = "zh-cn"
defaultContentLanguageInSubdir = true

[languages]
  [languages.en]
    weight = 1
    title = "Uni Alien"
    languageCode = "en"
    languageName = "English"
    [[languages.en.menu.main]]
      identifier = "posts"
      pre = ""
      post = ""
      name = "Posts"
      url = "/posts/"
      title = ""
      weight = 1
    [[languages.en.menu.main]]
      identifier = "tags"
      pre = ""
      post = ""
      name = "Tags"
      url = "/tags/"
      title = ""
      weight = 2
    [[languages.en.menu.main]]
      identifier = "categories"
      pre = ""
      post = ""
      name = "Categories"
      url = "/categories/"
      title = ""
      weight = 3
    [[languages.en.menu.main]]
      identifier = "series"
      pre = ""
      post = ""
      name = "Series"
      url = "/series/"
      title = ""
      weight = 4
    [[languages.en.menu.main]]
      identifier = "authors"
      pre = ""
      post = ""
      name = "Authors"
      url = "/authors/"
      title = ""
      weight = 5
    [[languages.en.menu.main]]
      identifier = "documentation"
      pre = ""
      post = ""
      name = "Docs"
      url = "/categories/documentation/"
      title = ""
      weight = 7
    [[languages.en.menu.main]]
      identifier = "about"
      pre = ""
      post = ""
      name = "About"
      url = "/about/"
      title = ""
      weight = 8
    [[languages.en.menu.main]]
      identifier = "github"
      pre = "<svg class='icon' xmlns='http://www.w3.org/2000/svg' viewBox='0 0 496 512'><path d='M165.9 397.4c0 2-2.3 3.6-5.2 3.6-3.3.3-5.6-1.3-5.6-3.6 0-2 2.3-3.6 5.2-3.6 3-.3 5.6 1.3 5.6 3.6zm-31.1-4.5c-.7 2 1.3 4.3 4.3 4.9 2.6 1 5.6 0 6.2-2s-1.3-4.3-4.3-5.2c-2.6-.7-5.5.3-6.2 2.3zm44.2-1.7c-2.9.7-4.9 2.6-4.6 4.9.3 2 2.9 3.3 5.9 2.6 2.9-.7 4.9-2.6 4.6-4.6-.3-1.9-3-3.2-5.9-2.9zM244.8 8C106.1 8 0 113.3 0 252c0 110.9 69.8 205.8 169.5 239.2 12.8 2.3 17.3-5.6 17.3-12.1 0-6.2-.3-40.4-.3-61.4 0 0-70 15-84.7-29.8 0 0-11.4-29.1-27.8-36.6 0 0-22.9-15.7 1.6-15.4 0 0 24.9 2 38.6 25.8 21.9 38.6 58.6 27.5 72.9 20.9 2.3-16 8.8-27.1 16-33.7-55.9-6.2-112.3-14.3-112.3-110.5 0-27.5 7.6-41.3 23.6-58.9-2.6-6.5-11.1-33.3 2.6-67.9 20.9-6.5 69 27 69 27 20-5.6 41.5-8.5 62.8-8.5s42.8 2.9 62.8 8.5c0 0 48.1-33.6 69-27 13.7 34.7 5.2 61.4 2.6 67.9 16 17.7 25.8 31.5 25.8 58.9 0 96.5-58.9 104.2-114.8 110.5 9.2 7.9 17 22.9 17 46.4 0 33.7-.3 75.4-.3 83.6 0 6.5 4.6 14.4 17.3 12.1C428.2 457.8 496 362.9 496 252 496 113.3 383.5 8 244.8 8zM97.2 352.9c-1.3 1-1 3.3.7 5.2 1.6 1.6 3.9 2.3 5.2 1 1.3-1 1-3.3-.7-5.2-1.6-1.6-3.9-2.3-5.2-1zm-10.8-8.1c-.7 1.3.3 2.9 2.3 3.9 1.6 1 3.6.7 4.3-.7.7-1.3-.3-2.9-2.3-3.9-2-.6-3.6-.3-4.3.7zm32.4 35.6c-1.6 1.3-1 4.3 1.3 6.2 2.3 2.3 5.2 2.6 6.5 1 1.3-1.3.7-4.3-1.3-6.2-2.2-2.3-5.2-2.6-6.5-1zm-11.4-14.7c-1.6 1-1.6 3.6 0 5.9 1.6 2.3 4.3 3.3 5.6 2.3 1.6-1.3 1.6-3.9 0-6.2-1.4-2.3-4-3.3-5.6-2z'/>" 
      post = ""
      name = ""
      url = "https://github.com/UnicornUMR1314"
      title = "GitHub"
      weight = 9

  [languages.zh-cn]
    weight = 2
    title = "Uni星人"
    languageCode = "zh-CN"
    languageName = "简体中文"
    hasCJKLanguage = true
    [[languages.zh-cn.menu.main]]
      identifier = "posts"
      pre = ""
      post = ""
      name = "文章"
      url = "/posts/"
      title = ""
      weight = 1
    [[languages.zh-cn.menu.main]]
      identifier = "tags"
      pre = ""
      post = ""
      name = "标签"
      url = "/tags/"
      title = ""
      weight = 2
    [[languages.zh-cn.menu.main]]
      identifier = "categories"
      pre = ""
      post = ""
      name = "分类"
      url = "/categories/"
      title = ""
      weight = 3
    [[languages.zh-cn.menu.main]]
      identifier = "series"
      pre = ""
      post = ""
      name = "系列"
      url = "/series/"
      title = ""
      weight = 4
    [[languages.zh-cn.menu.main]]
      identifier = "authors"
      pre = ""
      post = ""
      name = "作者"
      url = "/authors/"
      title = ""
      weight = 5
    [[languages.zh-cn.menu.main]]
      identifier = "documentation"
      pre = ""
      post = ""
      name = "文档"
      url = "/categories/documentation/"
      title = ""
      weight = 7
    [[languages.zh-cn.menu.main]]
      identifier = "about"
      pre = ""
      post = ""
      name = "关于"
      url = "/about/"
      title = ""
      weight = 8
    [[languages.zh-cn.menu.main]]
      identifier = "github"
      pre = "<svg class='icon' xmlns='http://www.w3.org/2000/svg' viewBox='0 0 496 512'><path d='M165.9 397.4c0 2-2.3 3.6-5.2 3.6-3.3.3-5.6-1.3-5.6-3.6 0-2 2.3-3.6 5.2-3.6 3-.3 5.6 1.3 5.6 3.6zm-31.1-4.5c-.7 2 1.3 4.3 4.3 4.9 2.6 1 5.6 0 6.2-2s-1.3-4.3-4.3-5.2c-2.6-.7-5.5.3-6.2 2.3zm44.2-1.7c-2.9.7-4.9 2.6-4.6 4.9.3 2 2.9 3.3 5.9 2.6 2.9-.7 4.9-2.6 4.6-4.6-.3-1.9-3-3.2-5.9-2.9zM244.8 8C106.1 8 0 113.3 0 252c0 110.9 69.8 205.8 169.5 239.2 12.8 2.3 17.3-5.6 17.3-12.1 0-6.2-.3-40.4-.3-61.4 0 0-70 15-84.7-29.8 0 0-11.4-29.1-27.8-36.6 0 0-22.9-15.7 1.6-15.4 0 0 24.9 2 38.6 25.8 21.9 38.6 58.6 27.5 72.9 20.9 2.3-16 8.8-27.1 16-33.7-55.9-6.2-112.3-14.3-112.3-110.5 0-27.5 7.6-41.3 23.6-58.9-2.6-6.5-11.1-33.3 2.6-67.9 20.9-6.5 69 27 69 27 20-5.6 41.5-8.5 62.8-8.5s42.8 2.9 62.8 8.5c0 0 48.1-33.6 69-27 13.7 34.7 5.2 61.4 2.6 67.9 16 17.7 25.8 31.5 25.8 58.9 0 96.5-58.9 104.2-114.8 110.5 9.2 7.9 17 22.9 17 46.4 0 33.7-.3 75.4-.3 83.6 0 6.5 4.6 14.4 17.3 12.1C428.2 457.8 496 362.9 496 252 496 113.3 383.5 8 244.8 8zM97.2 352.9c-1.3 1-1 3.3.7 5.2 1.6 1.6 3.9 2.3 5.2 1 1.3-1 1-3.3-.7-5.2-1.6-1.6-3.9-2.3-5.2-1zm-10.8-8.1c-.7 1.3.3 2.9 2.3 3.9 1.6 1 3.6.7 4.3-.7.7-1.3-.3-2.9-2.3-3.9-2-.6-3.6-.3-4.3.7zm32.4 35.6c-1.6 1.3-1 4.3 1.3 6.2 2.3 2.3 5.2 2.6 6.5 1 1.3-1.3.7-4.3-1.3-6.2-2.2-2.3-5.2-2.6-6.5-1zm-11.4-14.7c-1.6 1-1.6 3.6 0 5.9 1.6 2.3 4.3 3.3 5.6 2.3 1.6-1.3 1.6-3.9 0-6.2-1.4-2.3-4-3.3-5.6-2z'/>" 
      post = ""
      name = ""
      url = "https://github.com/UnicornUMR1314"
      title = "GitHub"
      weight = 9

[outputs]
home = ["HTML", "RSS", "JSON"]
page = ["HTML", "MarkDown"]
section = ["HTML", "RSS"]
taxonomy = ["HTML", "RSS"]

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [["\\[", "\\]"]]
          inline = [["\\(", "\\)"]]

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[taxonomies]
author = "authors"
category = "categories"
tag = "tags"
series = "series"